apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zirconsys-k8s
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  selector:
    matchLabels:
      type: "minikube-pv-k8s"
  accessModes:
    - ReadWriteOnce
