apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: zirconsys-k8s-space
  region: eu-central-1

nodeGroups:
  - name: zirc-1
    instanceType: t2.medium
    labels: { role: worker }   
    desiredCapacity: 1
    volumeSize: 20
  - name: zirc-2
    instanceType: t2.medium
    labels: { role: worker }   
    desiredCapacity: 1
    volumeSize: 20
