apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  labels:
    app: kuber
spec:
  selector:
    matchLabels:
      app: http-server
  replicas: 1
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: kuber-app
        image: "bakavets/kuber:v3.0"
        envFrom:
        - prefix: config_dev
          configMapRef:
            name: kuber-app-cm
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 8000
          name: http
      restartPolicy: Always
